---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.95.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.39.2
