---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.149.1 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.26.0
