---
name: Check files
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! diff <(find pkgs -name registry.yaml -print0 | xargs -0 dirname | sort -u) <(find pkgs -name pkg.yaml -print0 | xargs -0 dirname | sort -u); then
            echo "" >&2
            echo "::error::Either pkg.yaml or registry.yaml isn't found. Don't forget to add pkg.yaml for test" >&2
            exit 1
          fi
