---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  AQUA_LOG_COLOR: always
jobs:
  test:
    strategy:
      matrix:
        env:
          - runs-on: windows-latest
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: ubuntu-latest
            goarch: arm64
          - runs-on: ubuntu-latest
            goos: darwin
            goarch: arm64
          - runs-on: windows-latest
            goarch: arm64
    runs-on: ${{ matrix.env.runs-on }}
    defaults:
      run:
        shell: bash
    env:
      AQUA_CONFIG: aqua/test.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.1
        with:
          aqua_version: v1.18.0

      - uses: aquaproj/registry-action/test@v0.1.0
        with:
          goos: ${{ matrix.env.goos }}
          goarch: ${{ matrix.env.goarch }}
          go_version: "1.18.5"

  # This job is used for branch protection rule
  # Add this job to `Status checks that are required`
  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
